server:
  port: 8080

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1

        - id: customer_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/customer/**
          filters:
            - StripPrefix=1

        - id: enterprise_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/enterprise/**
          filters:
            - StripPrefix=1

        - id: event_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/event/**
          filters:
            - StripPrefix=1

        - id: booking_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/booking/**
          filters:
            - StripPrefix=1