server:
  port: 8082
  servlet:
    context-path: /customer

spring:
  application:
    name: customer-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/customer_service?createDatabaseIfNotExist=true}
    #    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${SPRING_DATASOURCE_USERNAME:root}
    # password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
